### ISSUE TITLE
Question about CUDA driver update/downgrade.

### ISSUE THREAD

**Issue by sakaia** [NVIDIA/deepops#1017]
DeepOps considers Kubernetes intallation and upgrade and downgrade.
It also considers CUDA driver installation. 
Is this also consider driver update and downgrade?
 
Reference 
https://github.com/NVIDIA/deepops/blob/master/docs/k8s-cluster/README.md

**Comment by supertetelman** [comment]
NVIDIA driver upgrades are handled in the standard Upgrade workflow where you are expected to run the k8s-cluster.yml playbook and follow the Kubespray update steps.

If you would like to upgrade Drivers out-of-band of DeepOps or Kubernetes this can be done using the nvidia-driver.yml playbook: https://github.com/NVIDIA/deepops/blob/master/playbooks/nvidia-software/nvidia-driver.yml

If you are using the GPU Operator rather than baremetal drivers, you driver versions are managed via Helm with upgrades to the GPU Operator itself.
