### ISSUE TITLE
What is disadvantages of hybrid cluster ( k8s and slurm in each node) ?

### ISSUE THREAD

**Issue by benzjakk** [NVIDIA/deepops#1034]
Can I run k8s and slurm with maximal performance ?
thx.

**Comment by ajdecon** [comment]
The big disadvantage of a hybrid cluster is that the two schedulers are not aware of each other. This means that both Slurm and Kubernetes will try to manage all the resources on each node where they're running, without regard to what the other scheduler is doing.

For example, on a node where both schedulers are active, each of Slurm and Kubernetes may try to schedule a job on the same GPU. The two jobs may conflict with each other, or fail to get the expected performance.

In most hybrid clusters, the system administrator will try to configure the nodes so that they are only active in one scheduler at a time. For example, if a node is running Kubernetes jobs, the sysadmin will [drain the node in Slurm](https://www.advancedclustering.com/act_kb/tech-tip-taking-compute-nodes-down-for-maintenance/#:~:text=qmod%20-e%20*%40node01-,Slurm%3A,-Modify%20the%20state); or if they want to run a Slurm job, they'll [drain the node in Kubernetes](https://kubernetes.io/docs/tasks/administer-cluster/safely-drain-node/).

However, this is a manual process, and makes hybrid clusters more difficult to manage.

**Comment by arnoldas500** [comment]
For a hybrid cluster, can slurm or k8s be installed first and the other added on later using [DeepOps Slurm Deployment Guide](https://github.com/NVIDIA/deepops/blob/master/docs/slurm-cluster) followed by [DeepOps Kubernetes Deployment Guide](https://github.com/NVIDIA/deepops/blob/master/docs/k8s-cluster)? Or does the installation for the hybrid cluster need to be done using the [DeepOps DGX POD Deployment Guide](https://github.com/NVIDIA/deepops/blob/master/docs/deepops/dgx-pod.md)? Asking because the documentation for the hybrid cluster is for ubuntu 18.04 and not updated to 20.04 like the stand alone k8s and slurm deployment options.
