### ISSUE TITLE
Deployment failed

### ISSUE THREAD

**Issue by DINESHKUMAR-DK** [NVIDIA/deepops#1130]
TASK [kubernetes/preinstall : Stop if either kube_control_plane or kube_node group is empty] ****************************************************************************
ok: [mgmt01] => (item=kube_control_plane) => changed=false
  ansible_loop_var: item
  item: kube_control_plane
  msg: All assertions passed
**failed: [mgmt01] (item=kube_node) => changed=false
  ansible_loop_var: item
  assertion: groups.get('kube_node')
  evaluated_to: false
  item: kube_node
  msg: Assertion failed**

NO MORE HOSTS LEFT ******************************************************************************************************************************************************

PLAY RECAP **************************************************************************************************************************************************************
mgmt01                     : ok=108  changed=6    unreachable=0    failed=1    skipped=126  rescued=0    ignored=1

**Comment by ajdecon** [comment]
@DINESHKUMAR-DK : It's not clear from just this snippet what might have failed.

However, this looks like *maybe* the playbooks is complaining because you don't have any hosts in the `[kube-node]` group? Our Kubernetes deployment requires that hosts be present in all of the `[kube-master]`, `[etcd]`, and `[kube-node]` sections of the [inventory file](https://github.com/NVIDIA/deepops/blob/a7634befa4cc53d5e31f7ff38c07196759c96ff5/config.example/inventory). If you only have one host, you just put it in all three sections.

If that's not it, please share your full inventory file and full output from your Ansible run, preferably in a gist. And we can help debug from there.

**Comment by ajdecon** [comment]
Closing issue, please feel free to re-open if you're still running into this!
