### ISSUE TITLE
Ansible playbook Slurm Installation failed , slurm master fails to get nvidia-smi over ssh , OOB session shows the nvidia-output

### ISSUE THREAD

**Issue by karanveersingh5623** [NVIDIA/deepops#1192]
Hi Team

slurm master fails to get nvidia-smi over ssh , idrac session shows the nvidia-output , please refer to run.
please refer scrrenshots as well.

![image](https://user-images.githubusercontent.com/30921663/177030600-7c3fe942-0153-47a8-8751-0000d1862b41.png)

![image](https://user-images.githubusercontent.com/30921663/177030631-c1de044c-b6de-4262-ac16-a2548b856f60.png)

[Uploading run.log…]()
log

**Comment by karanveersingh5623** [comment]
@ajdecon , Please let me know if you need more information .

**Comment by ajdecon** [comment]
Note: It doesn't look like the `run.log` file actually showed up, it's just a link to this issue.

However, this is an issue that I've seen before so I think I know what's going on. 😄 

When a node is configured as a Slurm compute node, DeepOps will typically set up Slurm to manage access to the GPUs. Users running outside of a Slurm job will not be able to access the GPUs, and Slurm jobs will only be able to access the GPUs that they've been allocated.

This configuration is set up in `/etc/pam.d/sshd`:

```
# BEGIN ANSIBLE MANAGED BLOCK (ansible-role-slurm)
-account sufficient /lib/x86_64-linux-gnu/security/pam_slurm_adopt.so action_no_jobs=ignore
-account sufficient pam_listfile.so item=user sense=allow file=/etc/localusers
-account required /lib/x86_64-linux-gnu/security/pam_slurm_adopt.so
# END ANSIBLE MANAGED BLOCK (ansible-role-slurm)
```

This isn't applied when you go through iDRAC because the PAM configuration is specific to SSH.

If you want to disable this functionality, and allow general access to the GPUs for SSH users, you can remove those lines and set `slurm_enable_pam_slurm_adopt: false` in your DeepOps configuration.

**Comment by karanveersingh5623** [comment]
@ajdecon , thanks for your inputs :)
I commented 3 lines from  /etc/pam.d/sshd and changed the param  **slurm_enable_pam_slurm_adopt: false** in  roles/slurm/defaults/main.yml , still issue persists .
Also rebooted the server and tried checking nvidia-smi , no luck .
