### ISSUE TITLE
Error while trying for air gapped environment

### ISSUE THREAD

**Issue by saingithub** [NVIDIA/deepops#1239]
I am getting the following error while running the script to create tar file for an air gapped environment
failed: [127.0.0.1] (item={'name': 'ceph', 'repo': '', 'image': 'ceph/ceph', 'source': 'build', 'version': 'v14.2'}) => changed=false
  ansible_loop_var: item
  item:
    image: ceph/ceph
    name: ceph
    repo: ''
    source: build
    version: v14.2
  msg: 'state is present but all of the following are missing: source'

Could you please help me on this.

**Comment by supertetelman** [comment]
Air gapped installs of DeepOps are no longer supported and we have also dropped support of ceph in the current release because we were regularly having install issues like this that are difficult to workaround.

If you are still having this issue, you might just try removing the ceph entry from the air gap scripting and re-running it.
