### ISSUE TITLE
crictl does not respect proxy config

### ISSUE THREAD

**Issue by fecet** [NVIDIA/deepops#1248]
I failed at one download task every time:

```
FAILED - RETRYING: download_file | Validate mirrors (4 retries left).
FAILED - RETRYING: download_file | Validate mirrors (3 retries left).
FAILED - RETRYING: download_file | Validate mirrors (2 retries left).
FAILED - RETRYING: download_file | Validate mirrors (1 retries left).
failed: [node01 -> node01] (item=None) => changed=false
  attempts: 4
  censored: 'the output has been hidden due to the fact that ''no_log: true'' was specified for this result'
fatal: [node01 -> {{ download_delegate if download_force_cache else inventory_hostname }}]: FAILED! => changed=false
  censored: 'the output has been hidden due to the fact that ''no_log: true'' was specified for this result'
...ignoring

```
How can I know what's the task I failed? Or at least I can pass taskes that have been done?

**Comment by fecet** [comment]
The error located at the container pull task, namely,
```
/usr/local/bin/crictl pull k8s.gcr.io/pause:3.3
```
It keeps failing even setting proxy, and it seems an upstream problem per https://github.com/kubernetes-sigs/cri-tools/issues/336.

Any workaround?

**Comment by arnoldas500** [comment]
was this issue fixed?

**Comment by dholt** [comment]
Following up on this stale-closed issue as part of the resumed DeepOps release cadence, with the root cause: `crictl pull` is executed by the containerd daemon, not by your shell, so shell/Ansible proxy settings have no effect on image pulls — the daemon's systemd environment must carry the proxy. DeepOps (via Kubespray) does plumb this: setting the top-level `http_proxy` / `https_proxy` variables in `config/group_vars/all.yml` causes Kubespray to write a systemd proxy drop-in for containerd (and Docker), after which `crictl pull` works through the proxy. Note the distinction from the `proxy_env` dictionary, which only proxies Ansible task subprocesses — the top-level scalars are what the container runtime needs (we are adding a clarifying comment to the example config). Also, the specific failing image path (`k8s.gcr.io/pause`) is gone from current releases — pulls now target `registry.k8s.io`. Present in releases 26.05+.
