### ISSUE TITLE
Ports closed on docker startup

### ISSUE THREAD

**Issue by clemsgrs** [NVIDIA/deepops#1256]
Running dockers no longer have open ports when started. As a result, things like tensorboard, jupyer notebooks, and remote ssh interpreter can no longer be reached.

In my case, I'm trying to remotely debug code from within a docker container via VSCode. Here's the setup:

- kick off a Slurm job via `srun` (see full `srun` command at the end)
- this job fires up a docker container via the `--container-image` flag

Ultimately, I'd like be able to map a port of the host to port 22 so that I can edit my `~/.ssh/config` file and access the docker container within VSCode. 

NB: here's the complete `srun` command I'm using

```
srun \
  --ntasks=1 \
  --gpus=1 \
  --cpus-per-task=4 \
  --time=6-00:00:00 \
  --container-image=<docker_image> \
  --pty bash
```

**Comment by clemsgrs** [comment]
True, sorry for the confusion between Docker & Enroot.
Thanks for your answer. It's still unclear to me what I have to do to be able to kick off an Enroot image via `srun` and show the exposed ports & to which ports of the node the container is running on they've been mapped to.

Ideally I'd like to display something like:

```
Exposed ports:
22/tcp -> http://<node_name>:32795
8888/tcp -> http://<node_name>:32796
```

I assume I'd have to add a few lines in the Docker file to enable this.

**Comment by dholt** [comment]
There's no concept of exposing ports with Enroot. If you run a service on a port in the container, it will be available on the host as well. In your case you'll need to modify the SSH server configuration in your container to run on a port other than 22, otherwise when it tries to start it will find a conflicting SSH service from the host already using port 22.
