### ISSUE TITLE
node exporters don't work after initial run of slurm playbook

### ISSUE THREAD

**Issue by jsharpe** [NVIDIA/deepops#1267]
The node stat exporters don't work after an initial install until either docker has been restarted or the node rebooted.
I suspect the playbooks are just missing a restart of docker after setting up the exporters / ip_forwarding configuration on the node.

**Comment by jsharpe** [comment]
Not stale

**Comment by jsharpe** [comment]
Not stale

**Comment by dholt** [comment]
Following up on this stale-closed issue as part of the resumed DeepOps release cadence: root-caused and fixed in #1363 (merged). The container-based monitoring units declared `Requires=docker.service` without `PartOf=`, so any explicit Docker restart — which the NVIDIA container runtime configuration performs during a first `slurm-cluster.yml` run on GPU nodes, right after the node exporter comes up — propagated as a one-way stop and nothing restarted the exporters until reboot. That matches the "works after reboot / after docker restart cycle" behavior in this thread. With `PartOf=docker.service`, Docker restarts propagate as unit restarts; the fix was live-validated by reproducing the exact deploy sequence (exporter active at end of run, and auto-recovery after `systemctl restart docker`). Ships in the next release (26.09).
