### ISSUE TITLE
ERROR! 'include' is not a valid attribute for a Play

### ISSUE THREAD

**Issue by jerry-birdseye** [NVIDIA/deepops#1272]
System:
- Ubuntu 20.04 Desktop
- SSH configuration done and validated by Ansible
- Nvidia drivers installed
- Docker & Nvidia runtime installed

----------

I was following the guide in https://github.com/NVIDIA/deepops/tree/master/docs/k8s-cluster#installation-steps

Finished setup with `./scripts/setup.sh` and created the inventory

When I execute `ansible-playbook -l k8s-cluster playbooks/k8s-cluster.yml` I got the following error

```
ERROR! 'include' is not a valid attribute for a Play

The error appears to be in '/home/birdseye/deepops/playbooks/k8s-cluster.yml': line 25, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

# Install python required for Ansible
- include: bootstrap/bootstrap-python.yml
  ^ here
```

Everything else was stock

**Comment by jdr-vintra** [comment]
`include` is old syntax and remove in recent versions of Ansible, see https://github.com/ansible/ansible/issues/76686

Unfortunately you can't just replace it with the new syntax `import_playbook` because you'll get an error in `docker.yml`

```ERROR! this task 'import_playbook' has extra params...```

---

Just a guess, but I had this problem because `setup.sh` didn't run properly, since I had `virtualenv` installed using `pip` instead of through `apt` which is the method used in the installer. After `python3 -mpip uninstall virtualenv` I reran the installer and it worked. 

You can see your Ansible version by running `python3 -c "import ansible; print(ansible.__version__)"`. Without the `virtualenv` I had `2.13.10` and after activating with `source /opt/deepops/env/bin/activate` I have version `2.11.12`. The `import` syntax was removed in `2.12`.

I'm hoping someone from Nvidia can update this, but in the mean time you should check your `virtualenv`.

**Comment by dholt** [comment]
Following up on this older issue as part of the resumed DeepOps release cadence: the legacy `include:` playbook syntax that newer Ansible rejects has been fully removed — current master has zero remaining uses, and the repository now passes ansible-lint and syntax checks against modern Ansible (10.x era) as part of release QA (first done for release 26.05). Releases 26.05+ should not reproduce this. If a specific playbook still fails on a current release, please open a new issue with the playbook name.
