### ISSUE TITLE
KillWait default in slurm slurm

### ISSUE THREAD

**Issue by ilya-da** [NVIDIA/deepops#1317]
at this moment deault slurm 30 sec KillWait used,  but this may be insufficient for large parallel jobs to gracefully terminate.

to remind it define period in second between try to kill (for example because of timeout reached) by SIGTERM until  SIGKILL used.
SIGKILL may cause 

Deallocating GPU memory and closing GPU contexts take time, especially when multiple GPUs are involved, apart will most likely disk cleanup involved.
Allowing longer grace periods for job termination can help prevent data loss and ensure proper cleanup of resources, especially for large-scale applications that may require more time to save state and release resources.

**Comment by ilya-da** [comment]
#1318 possible solution

**Comment by dholt** [comment]
Following up on this stale-closed issue as part of the resumed DeepOps release cadence: this was addressed by your merged PR #1318 — the Slurm configuration template now explicitly sets `KillWait=120` instead of inheriting Slurm's 30-second default, giving large GPU jobs time to release memory and flush I/O between SIGTERM and SIGKILL. The issue was closed by the stale bot only because the PR didn't reference it with a closing keyword. Present on current master and in releases 26.05+ (and site-overridable in config). Thanks for the fix!
