### ISSUE TITLE
Scheduled Jenkins job to perform test with CentOS

### ISSUE THREAD

**Issue by ajdecon** [NVIDIA/deepops#197]
Right now we do a Jenkins build for each PR using Ubuntu as the base OS, but we want to support CentOS as well.

The build already takes ~24 minutes for a successful run, and we have limited test resources, so I don't necessarily want to do *both* for each PR. Would it be possible to have Jenkins run the same build for CentOS on some regular schedule, say 2-4 times a day, to catch regressions? Or provide a way to trigger a CentOS build ad-hoc for a given PR?

**Comment by michael-balint** [comment]
Totally agree with this. It seems like the best solution would be more generalized and allow us to run specific tests during a PR (in addition to basic tests). When master builds, we could run through the gamut of all tests.

A crude way of doing this would be to have some checks in the Jenkinsfile. If this branch is a PR, then check for PR-specific tests. If master, do the whole suite of tests.

I'll take a look when I get back. I'm sure there's got to be an existing solution for this w/ Jenkins. Perhaps by creating a duplicate pipeline and passing parameters.

**Comment by michael-balint** [comment]
@dholt @ajdecon - Thoughts?

**Proposal 0: A general solution which allows a contributor to run specific tests for their PR**

The Jenkinsfile would check a particular directory in the repository, `tests/pr-test` for a file that matches the branch name (ex: michael-balint.master). If found, this file would be used to override the current Jenkinsfile, allowing total flexibility over the pipeline stages. For RHEL testing, we could set the appropriate environment variable at the beginning. For other features, we could call specific tests after the cluster is set up.

The negative of this approach is that we will have stale Jenkinsfiles in `tests/pr-test` that are leftover. We could periodically purge this if it is a problem.

**Proposal 1: Set up a parallel RHEL pipeline in Jenkins that is run once per day**

By cloning the existing project in Jenkins, we would have `deepops` and `deepops-rhel`. We would modify the `deepops-rhel` to set the appropriate environment var / inject it such that we use RHEL instead of Ubuntu. The build would be scheduled to run once a day using the `master` branch. Otherwise, PR builds could be triggered by going to Jenkins and specifically selecting a build to run with RHEL.

**Comment by ajdecon** [comment]
For a first attempt, I think proposal 1 makes more sense if it's not difficult to set up.

Adding "override" sorts of files, as in proposal 0, provides flexibility which is nice. But I'm concerned exposing those as a generic testing mechanism for external contributors, given that only maintainers of the repo are allowed to make changes to the Jenkins tests.

The stale Jenkinsfiles do feel untidy to me, and are something extra to manage, but probably don't represent a functional problem.

**Comment by michael-balint** [comment]
One other thought for proposal 0: we could have a separate (perhaps private) repository for testing. This repository would contain the PR-specific tests (named by the same convention as above) and the Jenkinsfile would check there for tests. In this way, these overrides would not be a part of the main repository.

**Comment by michael-balint** [comment]
Sounds like we're more in favor of Proposal 1 though. Will take a crack at it.

**Comment by ajdecon** [comment]
That would work for me.

**Comment by michael-balint** [comment]
@dholt - any thoughts/preferences on P0 vs P1 before I proceed?

**Comment by ajdecon** [comment]
Fixed in #448
