### ISSUE TITLE
Rapids/Dask deployment doesn't work out of the box

### ISSUE THREAD

**Issue by dholt** [NVIDIA/deepops#218]
Couple of things that I think we should modify:

* Build fails here, I think it needs a path, i.e. `.` at the end of the command:
https://github.com/NVIDIA/deepops/blob/45f64b35d07cb9790e0598b3b24ee4a26e5ffd11/scripts/k8s_deploy_rapids_dask.sh#L35

* The deployment should not depend on a load balancer, since not everyone has the ability to hand out free IP ranges in their environment.

* The deployment should work out of the box, i.e. not require manually building and pushing a container. We have the "deepops" account on docker hub we could use, though the containers should ideally come from NGC or another public source if possible.

**Comment by michael-balint** [comment]
Also...

- It's great that the script checks to see if existing elements are already installed, but it should not have a blocking action asking to delete/skip. This prevents the script from being automatable (used by other scripts) since it requires human input. Instead, implement a cleanup flag that can be passed in with the script (and document it).

**Comment by supertetelman** [comment]
I've addressed most of these concerns.

I would still need to do a small amount of work to pull from DockerHub instead of building a fresh image. I would prefer to keep the fresh build for now so that we don't end up maintaining another copy of the RAPIDS containers with a slight shim on top.

**Comment by supertetelman** [comment]
Deprecated feature, closing this isssue.
