### ISSUE TITLE
Please show version info of the cuda and other software in Nvidia-Docker & Nvidia-Driver package in Ansible-Galaxy

### ISSUE THREAD

**Issue by zhangshuiyong** [NVIDIA/deepops#380]
I can not find any version info of cuda and other software in nvidia-docker & nvidia-driver package in Ansible-Galaxy.

https://galaxy.ansible.com/nvidia/nvidia_docker

https://galaxy.ansible.com/nvidia/nvidia_driver

**Comment by supertetelman** [comment]
The cuda version update pulls the `latest` version from the release branch specified in `nvidia_driver_ubuntu_branch` (450 as of this comment).
 

`

**Comment by supertetelman** [comment]
@lukeyeager , do you think we could add more explicit documentation here to make it more clear which driver will be installed for which version?

**Comment by lukeyeager** [comment]
As you know, each role allows the user to lock into a specific package version:
* https://github.com/NVIDIA/ansible-role-nvidia-docker/blob/v1.2.1/defaults/main.yml#L1
* https://github.com/NVIDIA/ansible-role-nvidia-driver/blob/v2.0.0/defaults/main.yml#L2

We could document this in each repo, with an example of how to lock to some recent version.

Keeping the READMEs up-to-date with the current version of each package will be installed seems untenable, since package update releases aren't managed by us, and since the answer will probably be different for each os and os_version.
