### ISSUE TITLE
Add NFS as a default StorageClass option

### ISSUE THREAD

**Issue by supertetelman** [NVIDIA/deepops#394]
**What:**
The only/default Storage Provider currently deployed alongside Rook is Ceph. This is currently one of two officially supported providers for Rook, however the NFS provider is in alpha and seems to work well enough to add to DeepOps.

**Why:**
Many of the clusters deployed with DeepOps are Deep Learning focused an on-prem focused. These use cases tend to rely on local NFS servers to distribute datasets, models, checkpoints, etc. across the clusters. Rather than distributing data across a cluster using Ceph, I think we should take advantage of the existing NFS clusters and modify our rook deployment to use NFS by default.

**How:**

./scripts/k8s_deploy_rook.sh # Reads from a config file and deploys NFS; exits if no NFS
./scripts/k8s_deploy_rook.sh --ceph # Runs as is with Ceph

In cases where users do not have a NFS server setup, one could easily be setup using the built-in NFS playbooks. We can point them to those playbooks in the exit message.

The only complication I see here is that we would have nfs-client.yml, nfs-server.yml, config/inventory, and config/group_vars/nfs.yml all with nfs configuration information. This is related to an existing issue about consolidating some of the configuration (https://github.com/NVIDIA/deepops/issues/322).

Supporint Rook documentation can be found here:
https://github.com/nfs-ganesha/nfs-ganesha/wiki
https://github.com/rook/rook

**Comment by ajdecon** [comment]
I like the idea of improving our NFS support under Kubernetes, but I think this issue conflates a few different workflows.

If the user already has an existing NFS server, this probably doesn't belong in the `k8s_deploy_rook.sh` script. IIUC, the [Rook NFS support](https://rook.io/docs/rook/v1.2/nfs-crd.html) is used to create an NFS server within the cluster, not mounting an external NFS server. For mounting an external NFS server, we should probably use a different script. It doesn't make sure to use a "rook" script if we're not creating a Rook storage system. :)

I do agree that our Rook script should allow us to select between NFS and Ceph, but I think Ceph should continue to be the default. This is both because Ceph is a stable storage provider (while NFS is still alpha), and because Ceph is more flexible and supports more different storage protocols.

**Comment by supertetelman** [comment]
We've seen some recent slowness/issues deploying Rook/Ceph on various AWS configurations. I'd like to prioritize this feature and make it the default when it is tested.

**Comment by supertetelman** [comment]
I'm repurposing this issue a little bit. The original goal here was to make a streamlined K8s install that relied on NFS. Initially the thought was that this could be done using the nfs back-end of Rook.

Rather than use Rook, I think we should be using the `nfs-client-provisioner`.

I propose the following:

1. We Move the `nfs_exports` config section to `config.examples/group_vars/k8s-cluster.yml` and set reasonable defaults.
2. We include the `nfs-server.yml` playbook in the `k8s-cluster.yml` playbook and set up an NFS server with every install. This should run on the first managment node with an option to skip the setup.
3. After K8s is come up, we do a `helm install --set storageClass.defaultClass=true --set nfs.server=x.x.x.x --set nfs.path=/exported/path stable/nfs-client-provisioner`  (using a new playbook similar to the existing helm-passthrough playbook/roles).
4. We then remove the rook-ceph install steps from a lot of the documentation

The end result of this is that every K8s install will have a default storageclass automatically setup and the user can easily disable this or point it to an existing nfs server.

**Comment by supertetelman** [comment]
I am working on an initial pass of this here: https://github.com/supertetelman/deepops/blob/nfs-provisioner/playbooks/k8s-cluster/nfs-client-provisioner.yml

**Comment by supertetelman** [comment]
https://github.com/NVIDIA/deepops/pull/756
