### ISSUE TITLE
Monitoring deployment script no longer works

### ISSUE THREAD

**Issue by supertetelman** [NVIDIA/deepops#410]
It looks like the files for the coreos helm charts have moved. The deployment script `k8s_deploy_monitoring.sh` now fails with:

```
helm repo add coreos https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/
Error: Looks like "https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/" is not a valid chart repository or cannot be reached: Failed to fetch https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/index.yaml : 403 Forbidden
```

This is highly repeatable and seems to impact all branches/releases.

It looks like behavior just started early this morning.

**Comment by JeffYFHuang** [comment]
I met same problem since yesterday.

helm repo add coreos https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/
Error: Looks like "https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/" is not a valid chart repository or cannot be reached: Failed to fetch https://s3-eu-west-1.amazonaws.com/coreos-charts/stable/index.yaml : 403 Forbidden
