### ISSUE TITLE
Ignore to install the GPU Driver

### ISSUE THREAD

**Issue by Kaka1127** [NVIDIA/deepops#656]
Do you have any option to skip the installing GPU Driver on General Server?

**Comment by ajdecon** [comment]
The [`nvidia-driver.yml` playbook](https://github.com/NVIDIA/deepops/blob/master/playbooks/nvidia-driver.yml) will [detect GPUs and only install the driver if it detects the hardware](https://github.com/NVIDIA/deepops/blob/master/playbooks/nvidia-driver.yml#L21). So the driver should not be installed on any servers without GPUs. If you see a case where that's happening, please let us know!

Note that the [`nvidia-cuda.yml` playbook](https://github.com/NVIDIA/deepops/blob/master/playbooks/nvidia-cuda.yml) is separate, and only installs the NVIDIA CUDA Toolkit for developing GPU applications. Because this installs development tools, rather than the driver, it will run on servers with and without GPUs, as many people will write and compile their code on regular login nodes and workstations.

If you're building a Slurm cluster, the `slurm-cluster.yml` playbook will respect a few different variables that allow you to turn on and off parts of the install, including the driver and CUDA installs. See the [example config](https://github.com/NVIDIA/deepops/blob/master/config.example/group_vars/slurm-cluster.yml#L39) for details.

**Comment by supertetelman** [comment]
I would add onto that, if you run with --skip_tags=nvidia_driver the nvidia-driver playbook Adam shared will not attempt to install or change the driver.
