### ISSUE TITLE
Standalone SLURM

### ISSUE THREAD

**Issue by itzsimpl** [NVIDIA/deepops#659]
I have a standalone DGX system, to which I have to provide direct ssh access for users. I also need to setup SLURM, as they need to be able to run SLURM jobs. 

I have installed SLURM via the deepops `playbooks/slurm-cluster.yml` playbook; where I put the DGX system as both the `slurm-master` and `slurm-node`. The setup was successful. 

In order to give ssh access to any other user I have to manually list them in `/etc/localusers` as well as `/etc/slurm/localusers.backup`. With that they can ssh to the system.

All users that can ssh to the system can run a SLURM job on it (e.g. `srun grep PRETTY /etc/os-release`), however, as soon as the job completes all their active connections (e.g. multiple ssh connections) to the system get terminated with a message `Connection to ... closed by remote host.`.

Any ideas how to solve this issue? 

I assume it has to do with `pam.d` and the `epilog.d` scripts, but I'm unable to pinpoint where exactly.

**Comment by dholt** [comment]
There’s an epilog script that kills any lingering processes from a user so they can’t leave things running when a job ends, see: https://github.com/NVIDIA/deepops/blob/master/roles/slurm/templates/etc/slurm/epilog.d/40-lastuserjob-processes

Normally you’d want to dedicate a second server as your login server where users submit jobs from, otherwise anyone can run jobs outside of the scheduler on the DGX.

**Comment by itzsimpl** [comment]
Perfect, this worked like a charm, I added the lines 
```
if grep -q -w "$SLURM_JOB_USER" /etc/slurm/localusers.backup ; then
    exit 0  # don't kill residual user processes
fi
```
before the check if `$SLURM_JOB_USER != root`.

You're right, however, this will let users run processes outside the scheduler; I will definitely also look into the possibility of adding a login node, thanks for the heads up.
