### ISSUE TITLE
osd on raw device failure cause rook-ceph version

### ISSUE THREAD

**Issue by h3z** [NVIDIA/deepops#668]
In version `tags/20.06.1` and `tags/20.08`, there is a bug.
When I install rook-ceph and provide a raw device, it should use the device to create osd. But the prepare pod shows that, "**not a block device**".

In version `tags/20.06`, it is no problem.

I check the log, and find that:
https://github.com/NVIDIA/deepops/blob/abdf5a892c2c5c80c5362f0a82aacd05998928fc/scripts/k8s/deploy_rook.sh#L9

```
commit 3fe218d2cf73f683b9f1876c561ca2999ca5020c
Author: Adam Tetelman <supertetelman@gmail.com>
Date:   Mon Jun 22 17:30:10 2020 -0700

    Revert "Fix Ceph StorageClass provisioning issues in AWS"

    The new Rook no longer supports directory based OSDs. This reverts commit 791b6a4bbb87232e22d265c7518ff55c5291b313.
```

```
commit b6a3fcd3fb04aec1df4c254f045f811c40d41a39
Author: yangatgithub <yangya@nvidia.com>
Date:   Fri May 29 22:11:55 2020 +0000

    Fix Ceph StorageClass provisioning issues in AWS
```

**Comment by h3z** [comment]
So..  it means there is a bug need upgrade version, and there is another bug need revert...
So..  what should going on..

**Comment by supertetelman** [comment]
The rook-ceph implementation currently in DeepOps is fairly out of date. We are keeping it that way so that we can use the `directory` volume option. This is mostly used as a development aid/stop-gap for deploying Kubeflow.

For any production-grade deployments relying on distributed storage or using a raw device I would recommend comparing the DeepOps code to the Rook examples and deploying a more up-to-date version. I would also recommend making a move over to NFS and looking into the nfs-provisioner.

I've had an open issue for a few months now to integrate the nfs provisioner into DeepOps so that we can replace Rook-Ceph as the default storage engine, but until now Ceph is there primarily for test reasons and to deploy Kubeflow.
