### ISSUE TITLE
Firewall rules keep blocking outside of traffic after teardown

### ISSUE THREAD

**Issue by SoheilSalehian** [NVIDIA/deepops#932]
Hello

After teardown of my single node cluster, the iptables's firewall rules (`bad-iptables.txt`) are overwritten at startup which is blocking many ports to access the machine. I'm running ubuntu 18.04 and ran the k8s-cluster.yaml ansible playbook.

Some more context:  after reseting the iptables (and flushing: `flush-iptables.txt`), I can get access but I can't seem to figure out which service during startup is causing the issue (even after purging). Persisting to reset iptables (using best practice) doesn't seem take effect neither.

Any ideas on finding what's still overwriting and removing it?

Thanks!

[flush-iptables.txt](https://github.com/NVIDIA/deepops/files/6326157/flush-iptables.txt)
[bad-iptables.txt](https://github.com/NVIDIA/deepops/files/6326158/bad-iptables.txt)

**Comment by ajdecon** [comment]
We set up Kubernetes using Kubespray. We don't do any other explicit iptables setup in DeepOps AFAIK, so I'm guessing these rules would have been added by Kubespray.

Kubespray does include a [reset playbook](https://github.com/kubernetes-sigs/kubespray/blob/master/reset.yml), which I'm guessing is what you used to tear down your cluster? But this is intended to allow you to redeploy Kubernetes, rather than intended to fully remove all cluster state.

Unfortunately, we don't have a full "uninstall" workflow for a Kubernetes cluster, and generally recommend re-imaging the machines where you installed the cluster.

This issue is a bit old, so I hope you were able to resolve the iptables issue!
