### ISSUE TITLE
Job exited abnormally

### ISSUE THREAD

**Issue by mast1986** [NVIDIA/deepops#992]
When the same user submits two jobs to the same node, the two jobs run at the same time. When one job finishes normally, the other job quits, but the job is not finished.

When I went to check /var/log/slurm/slurmctld.log, I found that when the first job ended normally, the second job received WEXITSTATUS 9, resulting in an abnormal exit.

So I wonder if DeepOPS will make some settings for slurm that will cause this problem to happen?

![image](https://user-images.githubusercontent.com/51349378/123978801-be1fcc00-d9f2-11eb-8bae-db3be852c684.png)

DeepOPS version: 20.12
Slurm version: 20.02.4

My test scripts as below:
**JOB1**
#!/bin/bash
#SBATCH -J df1
#SBATCH -p batch
#SBATCH -o job-%j.log
#SBATCH -e job-%j.err
#SBATCH -N 1
#SBATCH -w slurm-gpu
echo "df1 job "
hostname
date
sleep 30
date

**JOB2**
#!/bin/bash
#SBATCH -J df2
#SBATCH -p batch
#SBATCH -o job-%j.log
#SBATCH -e job-%j.err
#SBATCH -N 1
#SBATCH -w slurm-gpu
echo "df2 job "
hostname
date
sleep 60
date

**Comment by ajdecon** [comment]
This isn't intended behavior, and in general this shouldn't happen. I just ran a test on my dev system, based on your job scripts above, and wasn't able to reproduce the problem.

The only thing I can think of is that Slurm may have incorrectly terminated the second job when the first one exited. We have an [epilog script](https://github.com/NVIDIA/deepops/blob/master/roles/slurm/templates/etc/slurm/epilog.d/40-lastuserjob-processes) to clean up left-over user processes after a job exits, but this should only execute when there are no jobs from that user left on the node.

Can you share the relevant lines from `/var/log/slurm/slurmd.log` and `/var/log/slurm/prolog-epilog` on the node where these jobs ran?

If you want to test the epilog script theory, you can also try removing `/etc/slurm/epilog.d/40-lastuserjob-processes` from the node you're testing and see if the problem reproduces.

**Comment by mast1986** [comment]
Hi Adam,

Thank you for your reply, here are the slurmd.log and prolog-epilog:
**slurmd.log**
![12488](https://user-images.githubusercontent.com/51349378/124055706-f78a2300-da56-11eb-9a1d-3261f10452d3.png)
**prolog-epilog**
![image](https://user-images.githubusercontent.com/51349378/124052356-d6becf00-da50-11eb-869f-35c396c8d9ac.png)

In addition, as you suggested, we try removing /etc/slurm/epilog.d/40-lastuserjob-processes from the node, and there is no job exit.

Also, we have test on our dev system, wasn't able to reproduce the problem too.
We compared two system scripts /etc/slurm/epilog.d/40-lastuserjob-processes, which are the same:
<img width="397" alt="40-lastuserjob-processes" src="https://user-images.githubusercontent.com/51349378/124055293-32d82200-da56-11eb-87d2-633ff5429969.png">

Although try removing /etc/slurm/epilog.d/40-lastuserjob-processes of makes the problem seem to be solved, I still want to know why, and what is the effect of removing /etc/slurm/epilog.d/40-lastuserjob-processes?

Thank you Adam

**Comment by ajdecon** [comment]
The `40-lastuserjob-processes` script is intended to clean up leftover processes after a job completes. However, it's only supposed to run if there are no other jobs on the node, so something is wrong.

Our general "epilog" flow to clean up after jobs complete looks like this:

1. When a Slurm job finishes, Slurm invokes our epilog script (`/etc/slurm/epilog.sh`)
2. The epilog script runs `/etc/slurm/shared/bin/run-parts.sh /etc/slurm/epilog.d`
3. `run-parts.sh` parses the names of all the scripts in `/etc/slurm/epilog.d`, and runs them if they match some conditions. For example, scripts with `lastuserjob` in the name should only be executed if the job that completed was the last job on the node.

In this case, clearly something is wrong because `40-lastuserjob-processes` is being executed when another job is on the node. Because we can't reproduce this on either your dev system or my test system, there's something different on the system where you see the problem.

At this point, given that you've removed the script, you shouldn't see this problem going forward. The only downside to that solution is that jobs which don't exit correctly may leave processes behind on the node.

If you want to try restoring this script, I'd recommend re-running Ansible using the DeepOps 21.06 release to make sure you have the most recent version of the code. We can then see if the problem repeats itself.

**Comment by mast1986** [comment]
Thanks Adam!
